select ceil(8.29) from dual;
select ceil(-3.9) from dual;
select ceil(17/3) from dual;
select floor(9.76) from dual;
select floor(-5.3) from dual;
select floor(15/4) from dual;
select sqrt(625) from dual;
select sqrt(2) from dual;
select abs(8.29) from dual;
select abs(-3.14) from dual;
select abs(-42) from dual;
select sysdate as now from dual;
select to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') from dual;
select systimestamp from dual;
select LEAST('hello','good','morning') from dual;
select greatest('hello','good','morning') from dual;
select trim(leading ' ' from ' trim me') from dual;
select trim(trailing ' ' from 'i love india') from dual;
select rpad('agnus', 15, 'x') from dual;
select rpad(123, 6, '0') from dual;
select reverse('uoyevoli') from dual;
select to_Char('PALINDROME') from DUAL where 'racecar' = reverse('racecar');
select length('oracle database') from dual;
select concat(concat(concat(concat('oracle', ' '), 'sql'), ' '), concat(concat('is', ' '), concat('powerful', ' flexible'))) from dual;
select concat('Agnus', ' Jose') from dual;
select substr('india is my country', instr('india is my country', 'is'), 2) from dual;
select substr('agnus', length('agnus') / 2, 3) from dual;
select substr('substring', 1, 3) from dual;
